# Generated by Django 4.1.5 on 2023-02-01 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='desc',
            new_name='detials',
        ),
    ]
